import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Layout } from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/hooks/useAuth";
import {
  ShoppingCart,
  Package,
  Loader2,
  ChevronRight,
  ChevronLeft,
  Check,
  MapPin,
  CreditCard,
  FileText,
  Truck,
  Plus,
  Minus,
  X,
  CheckCircle2,
} from "lucide-react";

interface CartItem {
  id: string;
  name: string;
  part_number: string;
  unit_price: number;
  quantity: number;
  image_url: string | null;
}

const steps = [
  { id: 1, name: "Cart Review", icon: ShoppingCart },
  { id: 2, name: "Shipping", icon: MapPin },
  { id: 3, name: "GST & Billing", icon: FileText },
  { id: 4, name: "Order Summary", icon: CreditCard },
  { id: 5, name: "Confirmation", icon: CheckCircle2 },
];

export default function Checkout() {
  const navigate = useNavigate();
  const location = useLocation();
  const { user } = useAuth();
  const { toast } = useToast();
  
  const [currentStep, setCurrentStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [orderComplete, setOrderComplete] = useState(false);
  const [orderNumber, setOrderNumber] = useState("");
  
  // Cart state (passed from Components page via sessionStorage)
  const [cartItems, setCartItems] = useState<CartItem[]>([]);
  
  // Shipping form
  const [shipping, setShipping] = useState({
    name: "",
    phone: "",
    address: "",
    city: "",
    state: "",
    pincode: "",
  });
  
  // GST form
  const [billing, setBilling] = useState({
    gstNumber: "",
    sameAsShipping: true,
    billingAddress: "",
  });

  useEffect(() => {
    // Load cart from sessionStorage
    const savedCart = sessionStorage.getItem("checkout_cart");
    if (savedCart) {
      setCartItems(JSON.parse(savedCart));
    }
    
    // Load user profile for pre-filling
    if (user) {
      loadUserProfile();
    }
  }, [user]);

  const loadUserProfile = async () => {
    if (!user) return;
    
    const { data } = await supabase
      .from("profiles")
      .select("*")
      .eq("user_id", user.id)
      .single();
    
    if (data) {
      setShipping({
        name: data.contact_name || "",
        phone: data.phone || "",
        address: data.address || "",
        city: data.city || "",
        state: data.state || "",
        pincode: data.pincode || "",
      });
      setBilling({
        ...billing,
        gstNumber: data.gst_number || "",
      });
    }
  };

  const subtotal = cartItems.reduce((sum, item) => sum + item.unit_price * item.quantity, 0);
  const gstAmount = subtotal * 0.18;
  const shippingCost = subtotal >= 5000 ? 0 : 150;
  const total = subtotal + gstAmount + shippingCost;

  const updateQuantity = (id: string, delta: number) => {
    setCartItems(prev =>
      prev
        .map(item => item.id === id ? { ...item, quantity: Math.max(0, item.quantity + delta) } : item)
        .filter(item => item.quantity > 0)
    );
  };

  const removeItem = (id: string) => {
    setCartItems(prev => prev.filter(item => item.id !== id));
  };

  const validateStep = (step: number): boolean => {
    switch (step) {
      case 1:
        return cartItems.length > 0;
      case 2:
        return !!(shipping.name && shipping.phone && shipping.address && shipping.city && shipping.state && shipping.pincode);
      case 3:
        return true; // GST is optional
      case 4:
        return true;
      default:
        return true;
    }
  };

  const nextStep = () => {
    if (!validateStep(currentStep)) {
      toast({
        title: "Missing information",
        description: "Please fill in all required fields.",
        variant: "destructive",
      });
      return;
    }
    
    if (currentStep === 4) {
      submitOrder();
    } else {
      setCurrentStep(prev => Math.min(5, prev + 1));
    }
  };

  const prevStep = () => {
    setCurrentStep(prev => Math.max(1, prev - 1));
  };

  const submitOrder = async () => {
    if (!user) {
      toast({
        title: "Please login",
        description: "You need to be logged in to place an order.",
        variant: "destructive",
      });
      navigate("/auth");
      return;
    }

    setLoading(true);
    try {
      // Create the order - order_number is auto-generated by trigger
      const { data: order, error: orderError } = await supabase
        .from("component_orders")
        .insert([{
          user_id: user.id,
          order_number: `BCOMP-${Date.now()}`,
          subtotal,
          tax_amount: gstAmount,
          shipping_amount: shippingCost,
          total_amount: total,
          shipping_name: shipping.name,
          shipping_phone: shipping.phone,
          shipping_address: shipping.address,
          shipping_city: shipping.city,
          shipping_state: shipping.state,
          shipping_pincode: shipping.pincode,
          gst_number: billing.gstNumber || null,
          status: "pending",
        }])
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = cartItems.map(item => ({
        order_id: order.id,
        component_id: item.id,
        part_number: item.part_number,
        name: item.name,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.unit_price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from("component_order_items")
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Clear cart
      sessionStorage.removeItem("checkout_cart");
      
      setOrderNumber(order.order_number);
      setOrderComplete(true);
      setCurrentStep(5);

      toast({
        title: "Order placed successfully!",
        description: `Your order ${order.order_number} has been confirmed.`,
      });
    } catch (error) {
      console.error("Order submission error:", error);
      toast({
        title: "Order failed",
        description: "There was an error placing your order. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Layout>
      <section className="section-padding bg-gradient-to-b from-muted/30 to-background min-h-screen">
        <div className="container-wide">
          {/* Header */}
          <div className="mb-8">
            <h1 className="text-3xl font-bold text-foreground mb-2">Checkout</h1>
            <p className="text-muted-foreground">Complete your order in a few simple steps</p>
          </div>

          {/* Progress Steps */}
          <div className="mb-8">
            <div className="flex items-center justify-between">
              {steps.map((step, index) => (
                <div key={step.id} className="flex items-center flex-1">
                  <div className="flex flex-col items-center">
                    <div className={`w-10 h-10 rounded-full flex items-center justify-center transition-colors ${
                      currentStep >= step.id 
                        ? "bg-accent text-accent-foreground" 
                        : "bg-muted text-muted-foreground"
                    }`}>
                      {currentStep > step.id ? (
                        <Check className="w-5 h-5" />
                      ) : (
                        <step.icon className="w-5 h-5" />
                      )}
                    </div>
                    <span className={`text-xs mt-2 text-center hidden sm:block ${
                      currentStep >= step.id ? "text-foreground font-medium" : "text-muted-foreground"
                    }`}>
                      {step.name}
                    </span>
                  </div>
                  {index < steps.length - 1 && (
                    <div className={`flex-1 h-1 mx-2 rounded ${
                      currentStep > step.id ? "bg-accent" : "bg-muted"
                    }`} />
                  )}
                </div>
              ))}
            </div>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Main Content */}
            <div className="lg:col-span-2">
              {/* Step 1: Cart Review */}
              {currentStep === 1 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <ShoppingCart className="w-5 h-5" />
                      Review Your Cart
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    {cartItems.length === 0 ? (
                      <div className="text-center py-12">
                        <ShoppingCart className="w-16 h-16 text-muted-foreground mx-auto mb-4" />
                        <p className="text-muted-foreground mb-4">Your cart is empty</p>
                        <Button variant="outline" onClick={() => navigate("/components")}>
                          Continue Shopping
                        </Button>
                      </div>
                    ) : (
                      <div className="space-y-4">
                        {cartItems.map((item) => (
                          <div key={item.id} className="flex items-center gap-4 p-4 bg-muted/50 rounded-lg">
                            <div className="w-20 h-20 bg-muted rounded-lg flex items-center justify-center">
                              {item.image_url ? (
                                <img src={item.image_url} alt={item.name} className="w-16 h-16 object-contain" />
                              ) : (
                                <Package className="w-10 h-10 text-muted-foreground" />
                              )}
                            </div>
                            <div className="flex-1">
                              <p className="font-medium">{item.name}</p>
                              <p className="text-sm text-muted-foreground font-mono">{item.part_number}</p>
                              <p className="text-lg font-bold mt-1">₹{item.unit_price.toFixed(2)}</p>
                            </div>
                            <div className="flex items-center gap-2">
                              <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => updateQuantity(item.id, -1)}>
                                <Minus className="w-4 h-4" />
                              </Button>
                              <span className="w-8 text-center font-medium">{item.quantity}</span>
                              <Button variant="outline" size="icon" className="h-8 w-8" onClick={() => updateQuantity(item.id, 1)}>
                                <Plus className="w-4 h-4" />
                              </Button>
                              <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive ml-2" onClick={() => removeItem(item.id)}>
                                <X className="w-4 h-4" />
                              </Button>
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Step 2: Shipping Address */}
              {currentStep === 2 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <MapPin className="w-5 h-5" />
                      Shipping Address
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="grid sm:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="name">Full Name *</Label>
                        <Input
                          id="name"
                          value={shipping.name}
                          onChange={(e) => setShipping({ ...shipping, name: e.target.value })}
                          placeholder="Your full name"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="phone">Phone Number *</Label>
                        <Input
                          id="phone"
                          value={shipping.phone}
                          onChange={(e) => setShipping({ ...shipping, phone: e.target.value })}
                          placeholder="+91 98765 43210"
                        />
                      </div>
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="address">Street Address *</Label>
                      <Input
                        id="address"
                        value={shipping.address}
                        onChange={(e) => setShipping({ ...shipping, address: e.target.value })}
                        placeholder="Building, Street, Area"
                      />
                    </div>
                    <div className="grid sm:grid-cols-3 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="city">City *</Label>
                        <Input
                          id="city"
                          value={shipping.city}
                          onChange={(e) => setShipping({ ...shipping, city: e.target.value })}
                          placeholder="City"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="state">State *</Label>
                        <Input
                          id="state"
                          value={shipping.state}
                          onChange={(e) => setShipping({ ...shipping, state: e.target.value })}
                          placeholder="State"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label htmlFor="pincode">Pincode *</Label>
                        <Input
                          id="pincode"
                          value={shipping.pincode}
                          onChange={(e) => setShipping({ ...shipping, pincode: e.target.value })}
                          placeholder="560001"
                        />
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Step 3: GST & Billing */}
              {currentStep === 3 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <FileText className="w-5 h-5" />
                      GST & Billing Information
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="gst">GST Number (Optional)</Label>
                      <Input
                        id="gst"
                        value={billing.gstNumber}
                        onChange={(e) => setBilling({ ...billing, gstNumber: e.target.value.toUpperCase() })}
                        placeholder="22AAAAA0000A1Z5"
                        className="uppercase"
                      />
                      <p className="text-sm text-muted-foreground">
                        Enter your GSTIN for business invoicing. Leave blank for personal orders.
                      </p>
                    </div>
                    <div className="p-4 bg-accent/10 rounded-lg border border-accent/20">
                      <div className="flex items-center gap-2 mb-2">
                        <Truck className="w-5 h-5 text-accent" />
                        <span className="font-medium">Billing Address</span>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {shipping.name}<br />
                        {shipping.address}<br />
                        {shipping.city}, {shipping.state} - {shipping.pincode}<br />
                        Phone: {shipping.phone}
                      </p>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Step 4: Order Summary */}
              {currentStep === 4 && (
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                      <CreditCard className="w-5 h-5" />
                      Order Summary
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-6">
                    <div>
                      <h4 className="font-medium mb-3">Items ({cartItems.length})</h4>
                      <div className="space-y-2">
                        {cartItems.map((item) => (
                          <div key={item.id} className="flex justify-between text-sm">
                            <span>{item.name} x {item.quantity}</span>
                            <span>₹{(item.unit_price * item.quantity).toFixed(2)}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                    <Separator />
                    <div>
                      <h4 className="font-medium mb-3">Shipping Address</h4>
                      <p className="text-sm text-muted-foreground">
                        {shipping.name}<br />
                        {shipping.address}<br />
                        {shipping.city}, {shipping.state} - {shipping.pincode}<br />
                        Phone: {shipping.phone}
                      </p>
                    </div>
                    {billing.gstNumber && (
                      <>
                        <Separator />
                        <div>
                          <h4 className="font-medium mb-2">GST Number</h4>
                          <p className="text-sm font-mono">{billing.gstNumber}</p>
                        </div>
                      </>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Step 5: Confirmation */}
              {currentStep === 5 && (
                <Card>
                  <CardContent className="py-12 text-center">
                    <div className="w-20 h-20 bg-success/10 rounded-full flex items-center justify-center mx-auto mb-6">
                      <CheckCircle2 className="w-10 h-10 text-success" />
                    </div>
                    <h2 className="text-2xl font-bold mb-2">Order Confirmed!</h2>
                    <p className="text-muted-foreground mb-4">
                      Thank you for your order. We've sent a confirmation to your email.
                    </p>
                    <Badge className="text-lg py-2 px-4 mb-6">{orderNumber}</Badge>
                    <div className="flex gap-4 justify-center">
                      <Button variant="outline" onClick={() => navigate("/dashboard")}>
                        View Orders
                      </Button>
                      <Button className="bg-accent hover:bg-accent/90" onClick={() => navigate("/components")}>
                        Continue Shopping
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Navigation Buttons */}
              {currentStep < 5 && (
                <div className="flex justify-between mt-6">
                  <Button
                    variant="outline"
                    onClick={prevStep}
                    disabled={currentStep === 1}
                  >
                    <ChevronLeft className="w-4 h-4 mr-2" />
                    Back
                  </Button>
                  <Button
                    className="bg-accent hover:bg-accent/90"
                    onClick={nextStep}
                    disabled={loading || (currentStep === 1 && cartItems.length === 0)}
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Processing...
                      </>
                    ) : currentStep === 4 ? (
                      <>
                        Place Order
                        <Check className="w-4 h-4 ml-2" />
                      </>
                    ) : (
                      <>
                        Continue
                        <ChevronRight className="w-4 h-4 ml-2" />
                      </>
                    )}
                  </Button>
                </div>
              )}
            </div>

            {/* Order Summary Sidebar */}
            {currentStep < 5 && (
              <div className="lg:col-span-1">
                <Card className="sticky top-24">
                  <CardHeader>
                    <CardTitle>Order Total</CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="flex justify-between text-sm">
                      <span>Subtotal ({cartItems.reduce((sum, i) => sum + i.quantity, 0)} items)</span>
                      <span>₹{subtotal.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>GST (18%)</span>
                      <span>₹{gstAmount.toFixed(2)}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span>Shipping</span>
                      <span>{shippingCost === 0 ? "FREE" : `₹${shippingCost.toFixed(2)}`}</span>
                    </div>
                    {shippingCost === 0 && (
                      <Badge variant="outline" className="text-success border-success/30 bg-success/10">
                        Free shipping on orders above ₹5,000
                      </Badge>
                    )}
                    <Separator />
                    <div className="flex justify-between text-lg font-bold">
                      <span>Total</span>
                      <span>₹{total.toFixed(2)}</span>
                    </div>
                    <p className="text-xs text-muted-foreground">
                      Prices are inclusive of all applicable taxes.
                    </p>
                  </CardContent>
                </Card>
              </div>
            )}
          </div>
        </div>
      </section>
    </Layout>
  );
}
